### ISSUE TITLE
CLI kitchen sink and cordova fails

### ISSUE THREAD

**Issue by outofmemoryagain** [quasarframework/icongenie#62]
When running kitchen sink with the following in command
``` 
iconfactory -p=kitchensink -s="./favicon-white.png" -t="./outputFolder" -m=pngquant
```
it partially completes with the following error:
```
(node:350332) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at hexToRgb (C:\Users\kerry.huguet\AppData\Roaming\npm\node_modules\@quasar\quasar-app-extension-icon-factory\lib\index.js:124:13)
    at Object.splash (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\@quasar\quasar-app-extension-icon-factory\lib\index.js:335:13)
    at Object.cordova (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\@quasar\quasar-app-extension-icon-factory\lib\index.js:203:16)
(node:350332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:350332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by outofmemoryagain** [comment]
Can also reproduce when running 
```
iconfactory -p=cordova -s="./favicon-white.png" -t="./outputFolder" -m=pngquant
```

**Comment by hawkeye64** [comment]
@outofmemoryagain Can you test this again with the last release I did? When I took over the project and ran the tests, I saw this error and fixed it. Not sure if it is a good fix for all combinations. The kitchensink test did pass tho.

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
